// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bfast_cpp_closestfrom
IntegerVector bfast_cpp_closestfrom(const NumericVector& a, const NumericVector& b, const bool twosided);
RcppExport SEXP _bfast_bfast_cpp_closestfrom(SEXP aSEXP, SEXP bSEXP, SEXP twosidedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const bool >::type twosided(twosidedSEXP);
    rcpp_result_gen = Rcpp::wrap(bfast_cpp_closestfrom(a, b, twosided));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bfast_bfast_cpp_closestfrom", (DL_FUNC) &_bfast_bfast_cpp_closestfrom, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_bfast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
