# RcppExports
# Copyright (C) 2019  Dainius Masiliūnas, Marius Appel
#
# This file is part of Foobar.
#
# Foobar is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# Foobar is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <http://www.gnu.org/licenses/>.

# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' For all elements of a vector a, find the closest elements in a vector B and returns resulting indexes
#' @param a numeric vector, ordered
#' @param b numeric vector, ordered
#' @param twosided logical value, if false, indexes will always point to elements in b that are less than or equal to elements in a but not greater than.
#' @return integer vector of the same size as a with elements represnting indexes pointing to closest values in b
.bfast_cpp_closestfrom <- function(a, b, twosided) {
    .Call('_bfast_bfast_cpp_closestfrom', PACKAGE = 'bfast', a, b, twosided)
}

